"""empty message

Revision ID: d4dde1542cdc
Revises: a5cffa318ac2
Create Date: 2024-07-30 11:13:07.484351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dde1542cdc'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('race', sa.String(length=250), nullable=True),
    sa.Column('height', sa.String(length=250), nullable=True),
    sa.Column('eyes_color', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('local', sa.String(length=250), nullable=True),
    sa.Column('dimension', sa.String(length=250), nullable=True),
    sa.Column('color', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaceships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('color', sa.String(length=250), nullable=True),
    sa.Column('guns', sa.String(length=250), nullable=True),
    sa.Column('velocity', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('characters_fk', sa.Integer(), nullable=True),
    sa.Column('planet_fk', sa.Integer(), nullable=True),
    sa.Column('spaceships_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_fk'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_fk'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['spaceships_fk'], ['spaceships.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               nullable=True)
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('username')

    op.drop_table('favorites')
    op.drop_table('spaceships')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
